// Quick test script to verify email configuration
const nodemailer = require('nodemailer');

async function testEmailConfig() {
  const transporter = nodemailer.createTransporter({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });
  
  try {
    const testEmail = {
      from: process.env.EMAIL_FROM,
      to: process.env.EMAIL_TO,
      subject: '🚨 AlphaForge Executive Alert System - Test Email',
      html: `
        <h2>AlphaForge Email Notifications Active</h2>
        <p><strong>Status:</strong> ✅ CONFIGURED AND OPERATIONAL</p>
        
        <h3>What You'll Receive:</h3>
        <ul>
          <li><strong>Daily Reports (6 AM):</strong> Security summaries and business intelligence</li>
          <li><strong>Weekly Reports (Monday 8 AM):</strong> Board-level analysis and revenue pipeline</li>
          <li><strong>Critical Alerts (Real-time):</strong> High-value prospects and security incidents</li>
        </ul>
        
        <h3>Sample Alert:</h3>
        <div style="background: #f5f5f5; padding: 15px; border-left: 4px solid #cc0000;">
          <h4>🚨 Hedge Fund Detection</h4>
          <p><strong>Business Value:</strong> $480,000</p>
          <p><strong>Risk Score:</strong> 175/200</p>
          <p><strong>Action Required:</strong> Immediate executive attention</p>
        </div>
        
        <p>This test confirms your email notification system is working.</p>
        <p><em>Generated by AlphaForge Business Intelligence System</em></p>
      `
    };
    
    await transporter.sendMail(testEmail);
    console.log('✅ Test email sent successfully');
    return true;
  } catch (error) {
    console.error('❌ Email test failed:', error.message);
    return false;
  }
}

testEmailConfig();